### ISSUE TITLE
Kanyon fails to load environment variables when running in Codespaces

### ISSUE THREAD

**Issue by ermontgo** [ermontgo/kapitan#12]
When running inside GitHub Codespaces, Kanyon fails with the following error:

```
System.ArgumentException: An item with the same key has already been added. Key: RVM_PATH
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Kanyon.Configuration.EnvironmentManifestConfigurationProvider.Build(Dictionary`2 values) in /home/runner/work/kanyon/kanyon/src/Kanyon/Configuration/EnvironmentManifestConfigurationProvider.cs:line 14
   at Kanyon.ManifestProcessor.BuildConfiguration() in /home/runner/work/kanyon/kanyon/src/Kanyon/ManifestProcessor.cs:line 21
   at Kanyon.ManifestPipeline.ExecutePipeline(FileInfo file) in /home/runner/work/kanyon/kanyon/src/Kanyon/ManifestPipeline.cs:line 29
   at Kanyon.Program.OnExecuteAsync(CommandLineApplication app) in /home/runner/work/kanyon/kanyon/src/Kanyon/Program.cs:line 107
```

**Comment by ermontgo** [comment]
Fixed in #17
